
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.4'

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  
target 'Pianote2' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  
  #pod 'Firebase/Messaging', '~> 6.34.0'
end