require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'

target 'Pianote2' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  pod 'Firebase/Messaging', '~> 6.34.0'
end